# NumPy is a package used for numerical computations using Python.
# It is capable of handling multi-dimensional arrays.

### pip install numpy

In [1]:
a=[3,4,5,6,76]
b=[4,5,6,7,7]

c=a+b
c

[3, 4, 5, 6, 76, 4, 5, 6, 7, 7]

In [3]:
a=[[1,2],[2,3]]
b=[[1,2],[2,3]]

c=a+b
c

[[1, 2], [2, 3], [1, 2], [2, 3]]

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)
print("Length: ",len(x))

[1 2 3 4]
<class 'numpy.ndarray'>
1
Length:  4


In [ ]:
# Add element in numpy array
x=np.append(x,5)
print(x)

[1 2 3 4 5]


In [ ]:
# Multiple by 2

print(x*2)
print(x/2)
print(x-2)
print(x+2)

[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[-1  0  1  2  3]
[3 4 5 6 7]


In [4]:
import numpy as np

a=np.array([[1,2],[2,3]])
b=np.array([[1,2],[2,3]])

c=a+b
c

array([[2, 4],
       [4, 6]])

#Zero

In [ ]:
numbers=np.zeros(4)
matrix=np.zeros((4,3))
print(numbers)
print(matrix)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#One

In [ ]:
numbers=np.ones(4)
matrix=np.ones((4,3))
print(numbers)
print(matrix)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#Range

In [ ]:
age=np.arange(18)
print(age)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


#Diagonal

In [ ]:
diag=np.eye(4)
ageOf=np.eye(4,5)
print(diag)
print(ageOf)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


#Linspace-- Important

In [ ]:
points=np.linspace(1,10,num=5)
print(points)

[ 1.    3.25  5.5   7.75 10.  ]


#Rand

In [ ]:
# 0 to 1

randomAxis=np.random.rand(4)
print(randomAxis)

[0.93586152 0.98939333 0.66648505 0.46641589]


In [ ]:
ages=np.random.rand(3,5)
print(ages)

[[0.91269036 0.42245983 0.06537177 0.14851656 0.2204743 ]
 [0.21056345 0.4458901  0.58982209 0.32116358 0.02074289]
 [0.08963157 0.01966196 0.85658987 0.40964184 0.0260423 ]]


#Randn

In [ ]:
# + to - close to zero

ages=np.random.randn(4)
print(ages)

[-1.08836164  1.03000506  1.99537876  0.21770266]


# Randint -- imp

In [ ]:

# min max , samples
ages=np.random.randint(5,40,10)
print(ages)

[29 38 38 24 25 34 27 23 16  6]


In [ ]:
heights=np.array([1,2,3,4])
print("Datatype of Array: ", heights.dtype)

Datatype of Array:  int64


In [ ]:
floatArray=heights.astype(float)
print("Datatype of Array: ", floatArray.dtype)

Datatype of Array:  float64


#math operations

In [ ]:
heights=np.array([1,2,3,4])

print(np.pow(heights,2))
print(np.multiply(heights,3))
print(np.mod(heights,3))

[ 1  4  9 16]
[ 3  6  9 12]
[1 2 0 1]


In [ ]:
print("Min: ",np.min(heights))
print("Max: ",np.max(heights))
print("SQRT: ",np.sqrt(heights))
print("sin: ",np.sin(heights))
print("cos: ",np.cos(heights))

Min:  1
Max:  4
SQRT:  [1.         1.41421356 1.73205081 2.        ]
sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


#Reshaping

In [ ]:
heights=np.array([1,2,3,4,5,6])

reshaped=np.reshape(heights,(3,2))
print(reshaped)


[[1 2]
 [3 4]
 [5 6]]


# Indexing Slicing

In [ ]:
heights=np.array([1,2,3,4])

print(heights[2])
print(heights[1:4])
print(heights[::-1])
print(heights[:4])
print(heights[2:])

3
[2 3 4]
[4 3 2 1]
[1 2 3 4]
[3 4]


#Iteration

In [ ]:
for i in heights:
  print(i)

1
2
3
4


#Copy

In [ ]:
arr1=np.array([1,2,3,4])
arr2=arr1

arr2[2]=34

# This also changed arr1
print(arr1)
print(arr2)

[ 1  2 34  4]
[ 1  2 34  4]


In [ ]:
arr1=np.array([1,2,3,4])
arr2=arr1.copy()

arr2[2]=34

# This also changed arr1
print(arr1)
print(arr2)

[1 2 3 4]
[ 1  2 34  4]


#Concatenate

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])

arr3=np.concatenate((arr1,arr2))

print(arr3)

[1 2 3 4 3 4 5 6]


#Delete

In [ ]:
# Delete by index

arr1=np.array([1,2,3,4])
arr=np.delete(arr1,2)
print(arr)

[3 4 6]


#Multi Dimensional Arrays in Numpy


In [5]:
oneDim=np.array([1,2,3,4,5])
twoDim=np.array([[1,2,3],[2,3,4]])
threeDim=np.array([[[1,2],[2,3]],[[2,3],[3,3]]])

print(oneDim)
print("Dimension: ",oneDim.ndim)
print(twoDim)
print("Dimension: ",twoDim.ndim)
print(threeDim)
print("Dimension: ",threeDim.ndim)

[1 2 3 4 5]
Dimension:  1
[[1 2 3]
 [2 3 4]]
Dimension:  2
[[[1 2]
  [2 3]]

 [[2 3]
  [3 3]]]
Dimension:  3
